### ISSUE TITLE
PureTaboo not working

### ISSUE THREAD

**Issue by HeavyDinosaur** [PowerModder/Watchdog-Adult-Renamer#2]
![Screen Shot 2020-11-08 at 1 25 16 PM](https://user-images.githubusercontent.com/73781838/98483479-ff464000-21c5-11eb-8b6a-d2c70bff3a20.png)

**Comment by PowerModder** [comment]
Pure Taboo is not currently supported. The program finds the Site ID because it uses the Phoenix Adult array but it doesn't have the scraper and the searcher-renamer functions to actually rename and move the files.

**Comment by PowerModder** [comment]
I will add a list of supported sites but due to no time i didn't have documented it properly to upload the .md file.
